# Generated by Django 5.1.1 on 2024-10-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_answer_answer_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='isPublic',
            field=models.BooleanField(default=False),
        ),
    ]
