# Generated by Django 5.1.2 on 2024-11-04 13:20

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_ispublic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=100, validators=[course.models.validate_capitalize]),
        ),
    ]
