# Generated by Django 5.1.2 on 2024-11-05 17:29

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_quiz_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=50, unique=True, validators=[course.models.validate_capitalize]),
        ),
    ]
