# Generated by Django 5.1.2 on 2024-11-05 17:37

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=50, validators=[course.models.validate_capitalize]),
        ),
    ]
