# Generated by Django 5.1.2 on 2024-11-05 17:50

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_lesson_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=70, validators=[course.models.validate_capitalize]),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=70, unique=True, validators=[course.models.validate_capitalize]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=70, validators=[course.models.validate_capitalize]),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=70, validators=[course.models.validate_capitalize]),
        ),
    ]
