# Generated by Django 5.1.2 on 2024-11-05 18:04

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_article_title_alter_course_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[course.models.validate_capitalize]),
        ),
    ]
