# Generated by Django 5.1.1 on 2024-10-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_answer_answer_text_and_more'),
        ('user', '0003_remove_customuser_courses_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='courses',
            field=models.ManyToManyField(blank=True, through='user.Enrollment', to='course.course'),
        ),
    ]
